language: php

dist: xenial

os: linux

sudo: false

matrix:
  fast_finish: true
  include:
    - name: "PHP 8.0"
      php: 8.0
      #dist: trusty
      #dist: focal
      #dist: bionic
      dist: xenial
      env:
      - PHPUNIT_VERSION="^9.3"
      - COMPOSER_TEST_SCRIPT="test"
      - PHPSTAN=1
      - UPLOADCOVERAGE=0

    - name: "PHP 7.4, - With upload coverage"
      php: 7.4
      dist: xenial
      env:
      - PHPUNIT_VERSION="^8.0"
      - COMPOSER_TEST_SCRIPT="test"
      - PHPSTAN=1
      - UPLOADCOVERAGE=1

    - name: "PHP 7.0"
      php: 7.0
      dist: xenial
      env:
      - PHPUNIT_VERSION="^7.0"
      - COMPOSER_TEST_SCRIPT="test-41"
      - PHPSTAN=1
      - UPLOADCOVERAGE=0

    - name: "PHP 5.6"
      php: 5.6
      dist: trusty
      env:
      - PHPUNIT_VERSION="5.7.27"
      - COMPOSER_TEST_SCRIPT="test-41"
      - PHPSTAN=0
      - UPLOADCOVERAGE=0


before_script:
  - (composer self-update; true)
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev
  - composer install
  - if [[ $PHPSTAN == 1 ]]; then composer require --dev phpstan/phpstan:"^0.12.8"; fi

script:
  - composer test
  - if [[ $PHPSTAN == 1 ]]; then vendor/bin/phpstan analyse src --level=4; fi

after_script:
  - |
    if [[ $UPLOADCOVERAGE == 1 ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
