language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

dist:
  - trusty
  - xenial

sudo: false

before_script:
  - (composer self-update; true)
  - composer install

script:
  - composer test
